title: Privacy Policy
baseurl: ""                  # empty unless using subdirectory deployment
markdown: kramdown
theme: minima                # minimal default theme; alternatives available
permalink: pretty   # enables /path/ style URLs